// @ts-nocheck
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
const prisma = new PrismaClient();
function daysFromNow(n: number): Date { const d = new Date(); d.setDate(d.getDate() + n); d.setHours(0,0,0,0); return d; }
function daysAgo(n: number): Date { return daysFromNow(-n); }
function dateAtHour(base: Date, h: number, m = 0): Date { const d = new Date(base); d.setHours(h, m, 0, 0); return d; }
function pick<T>(a: T[]): T { return a[Math.floor(Math.random() * a.length)]; }
const PHOTOS = ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200','https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200','https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200','https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200','https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200'];
const FAC_IMGS = ['https://images.unsplash.com/photo-1546519638405-a5ea4985c1c3?w=800','https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800','https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800'];
const EVT_IMGS = ['https://images.unsplash.com/photo-1546519638405-a5ea4985c1c3?w=600','https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=600','https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600','https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600'];
const FIRST = ['Marcus','Sophia','Liam','Emma','Noah','Ava','Isabella','James','Mia','Ethan','Charlotte','Lucas'];
const LAST = ['Rivera','Chen','OBrien','Patel','Kim','Johnson','Garcia','Williams','Lee','Brown','Davis','Martinez'];
const GENDERS = ['male','male','male','male','male','male','female','female','female','female','female','female'];
const BRACKETS = ['18-24','18-24','18-24','25-34','25-34','25-34','35-44','35-44','35-44','45-54','45-54','45-54'];
const TIERS = ['standard','pro','standard','elite','standard','pro','standard','pro','elite','standard','pro','standard'];
const RATINGS = [0.8,1.2,1.5,2.0,1.8,2.5,1.1,2.8,1.6,0.9,2.2,1.4];
const GAMES = [5,25,40,80,60,120,15,100,50,3,90,30];
const SPORTS = ['basketball','soccer','tennis','pickleball','volleyball'];
function dobFor(b: string): Date { const y = new Date().getFullYear(); if (b==='18-24') return new Date(y-21,3,15); if (b==='25-34') return new Date(y-29,7,10); if (b==='35-44') return new Date(y-38,1,20); return new Date(y-48,11,5); }
async function main() {
console.log('Starting comprehensive test seed...');
const pw = await bcrypt.hash('Muster123!', 10);
const admin = await prisma.user.upsert({ where:{email:'admin@muster.test'}, update:{password:pw}, create:{email:'admin@muster.test',username:'admin_muster',password:pw,firstName:'Alex',lastName:'Admin',displayName:'Alex Admin',phoneNumber:'+12075550100',dateOfBirth:new Date('1985-03-15'),gender:'male',profileImage:PHOTOS[0],tierTag:'Admin',ageBracket:'35-44',role:'admin',membershipTier:'pro',currentRating:2.0,totalGamesPlayed:50,pickupGamesPlayed:30,leagueGamesPlayed:20,onboardingComplete:true,sportPreferences:['basketball','tennis']} as any });
const owner = await prisma.user.upsert({ where:{email:'owner@muster.test'}, update:{password:pw}, create:{email:'owner@muster.test',username:'facility_owner',password:pw,firstName:'Olivia',lastName:'Owner',displayName:'Olivia Owner',phoneNumber:'+12075550101',dateOfBirth:new Date('1980-07-22'),gender:'female',profileImage:PHOTOS[1],tierTag:'Owner',ageBracket:'35-44',role:'member',membershipTier:'pro',currentRating:1.5,totalGamesPlayed:10,pickupGamesPlayed:10,leagueGamesPlayed:0,onboardingComplete:true,sportPreferences:['basketball','tennis','soccer']} as any });
const commissioner = await prisma.user.upsert({ where:{email:'commissioner@muster.test'}, update:{password:pw}, create:{email:'commissioner@muster.test',username:'commissioner_c',password:pw,firstName:'Carlos',lastName:'Commissioner',displayName:'Carlos Commissioner',phoneNumber:'+12075550102',dateOfBirth:new Date('1988-11-05'),gender:'male',profileImage:PHOTOS[2],tierTag:'Commissioner',ageBracket:'35-44',role:'member',membershipTier:'pro',currentRating:2.2,totalGamesPlayed:75,pickupGamesPlayed:40,leagueGamesPlayed:35,onboardingComplete:true,sportPreferences:['basketball','soccer','tennis']} as any });
const players: any[] = [];
for (let i=0;i<12;i++) { const p = await prisma.user.upsert({ where:{email:`player${i+1}@muster.test`}, update:{password:pw}, create:{email:`player${i+1}@muster.test`,username:`player_${i+1}`,password:pw,firstName:FIRST[i],lastName:LAST[i],displayName:`${FIRST[i]} ${LAST[i]}`,phoneNumber:`+1207555${String(200+i+1).padStart(4,'0')}`,dateOfBirth:dobFor(BRACKETS[i]),gender:GENDERS[i],profileImage:PHOTOS[i%PHOTOS.length],tierTag:TIERS[i]==='elite'?'Elite':TIERS[i]==='pro'?'Pro':null,ageBracket:BRACKETS[i],role:'member',membershipTier:TIERS[i],currentRating:RATINGS[i],totalGamesPlayed:GAMES[i],pickupGamesPlayed:Math.floor(GAMES[i]*0.6),leagueGamesPlayed:Math.floor(GAMES[i]*0.4),onboardingComplete:true,sportPreferences:SPORTS.slice(0,2+(i%3))} as any }); players.push(p); }
console.log('Users created');
for (let i=0;i<12;i++) { const n=2+(i%3); for (let s=0;s<n;s++) { await prisma.playerSportRating.upsert({ where:{userId_sportType:{userId:players[i].id,sportType:SPORTS[s]}}, update:{}, create:{userId:players[i].id,sportType:SPORTS[s],overallRating:0.8+((i*3+s*7)%17)/10,overallPercentile:5+((i*7+s*13)%90),bracketRating:0.9+((i*5+s*3)%14)/10,bracketPercentile:10+((i*11+s*5)%82),overallEventCount:1+((i*3+s)%39),bracketEventCount:1+((i*2+s)%19),ageBracket:BRACKETS[i],rating:RATINGS[i],gamesPlayed:GAMES[i]} }); } }
for (const [idx,plan] of [[1,'pro'],[3,'league'],[5,'facility_basic']] as [number,string][]) { await prisma.subscription.upsert({ where:{userId:players[idx].id}, update:{}, create:{userId:players[idx].id,plan,status:'active',currentPeriodStart:daysAgo(15),currentPeriodEnd:daysFromNow(15)} }); }
await prisma.user.upsert({ where:{email:'dep1@muster.test'}, update:{}, create:{email:'dep1@muster.test',username:'jamie_dep',password:pw,firstName:'Jamie',lastName:LAST[0],displayName:'Jamie '+LAST[0],phoneNumber:'+12075550300',dateOfBirth:new Date(new Date().getFullYear()-14,5,10),gender:'male',profileImage:PHOTOS[0],ageBracket:'18-24',isDependent:true,guardianId:players[0].id,sportPreferences:['basketball','soccer'],onboardingComplete:true} as any });
await prisma.user.upsert({ where:{email:'dep2@muster.test'}, update:{}, create:{email:'dep2@muster.test',username:'riley_dep',password:pw,firstName:'Riley',lastName:LAST[0],displayName:'Riley '+LAST[0],phoneNumber:'+12075550301',dateOfBirth:new Date(new Date().getFullYear()-10,9,22),gender:'female',profileImage:PHOTOS[1],ageBracket:'18-24',isDependent:true,guardianId:players[0].id,sportPreferences:['tennis'],onboardingComplete:true} as any });
console.log('Dependents, ratings, subscriptions created');
const fac1 = await prisma.facility.create({ data:{ name:'Portland Athletic Center',description:'Premier indoor sports complex.',sportTypes:['basketball','volleyball'],amenities:['Parking','Locker Rooms','Showers','Cafe'],imageUrl:FAC_IMGS[0],rating:4.7,pricePerHour:55,isActive:true,isVerified:true,verificationStatus:'approved',accessInstructions:'Enter through main lobby on Congress St.',parkingInfo:'Free lot behind building.',minimumBookingHours:1,bufferTimeMins:15,slotIncrementMinutes:60,contactName:'Olivia Owner',contactPhone:'(207)555-0200',contactEmail:'info@portlandac.com',contactWebsite:'https://portlandac.com',noticeWindowHours:24,teamPenaltyPct:50,penaltyDestination:'facility',policyVersion:new Date().toISOString(),street:'100 Congress St',city:'Portland',state:'ME',zipCode:'04101',latitude:43.6591,longitude:-70.2568,ownerId:owner.id }});
const fac2 = await prisma.facility.create({ data:{ name:'Casco Bay Tennis Club',description:'Outdoor tennis and pickleball courts.',sportTypes:['tennis','pickleball'],amenities:['Parking','Restrooms','Pro Shop'],imageUrl:FAC_IMGS[1],rating:4.5,pricePerHour:40,isActive:true,isVerified:true,verificationStatus:'approved',accessInstructions:'Courts behind clubhouse.',parkingInfo:'Lot on Eastern Promenade.',minimumBookingHours:1,bufferTimeMins:10,slotIncrementMinutes:60,contactName:'Olivia Owner',contactPhone:'(207)555-0201',contactEmail:'info@cascobaytennis.com',contactWebsite:'https://cascobaytennis.com',noticeWindowHours:12,teamPenaltyPct:25,penaltyDestination:'facility',policyVersion:new Date().toISOString(),street:'200 Eastern Promenade',city:'Portland',state:'ME',zipCode:'04101',latitude:43.67,longitude:-70.245,ownerId:owner.id }});
const fac3 = await prisma.facility.create({ data:{ name:'Riverside Soccer Complex',description:'Outdoor fields for soccer and flag football.',sportTypes:['soccer','flag_football'],amenities:['Parking','Bleachers','Lighting'],imageUrl:FAC_IMGS[2],rating:4.2,pricePerHour:65,isActive:true,isVerified:false,verificationStatus:'pending',accessInstructions:'Fields at end of Riverside Dr.',parkingInfo:'Gravel lot on site.',minimumBookingHours:1,bufferTimeMins:15,slotIncrementMinutes:60,contactName:'Olivia Owner',contactPhone:'(207)555-0202',contactEmail:'info@riversidesoccer.com',contactWebsite:'https://riversidesoccer.com',noticeWindowHours:48,teamPenaltyPct:30,penaltyDestination:'split',policyVersion:new Date().toISOString(),street:'50 Riverside Dr',city:'South Portland',state:'ME',zipCode:'04106',latitude:43.635,longitude:-70.28,ownerId:owner.id }});
const cA=await prisma.facilityCourt.create({data:{facilityId:fac1.id,name:'Court A',sportType:'basketball',capacity:10,isIndoor:true,isActive:true,displayOrder:1}});
const cB=await prisma.facilityCourt.create({data:{facilityId:fac1.id,name:'Court B',sportType:'basketball',capacity:10,isIndoor:true,isActive:true,displayOrder:2}});
const cV=await prisma.facilityCourt.create({data:{facilityId:fac1.id,name:'Volleyball Court',sportType:'volleyball',capacity:12,isIndoor:true,isActive:true,displayOrder:3}});
const cT1=await prisma.facilityCourt.create({data:{facilityId:fac2.id,name:'Court 1',sportType:'tennis',capacity:2,isIndoor:false,isActive:true,displayOrder:1}});
const cT2=await prisma.facilityCourt.create({data:{facilityId:fac2.id,name:'Court 2',sportType:'pickleball',capacity:4,isIndoor:false,isActive:true,displayOrder:2}});
const fA=await prisma.facilityCourt.create({data:{facilityId:fac3.id,name:'Field A',sportType:'soccer',capacity:22,isIndoor:false,isActive:true,displayOrder:1}});
const fB=await prisma.facilityCourt.create({data:{facilityId:fac3.id,name:'Field B',sportType:'flag_football',capacity:14,isIndoor:false,isActive:true,displayOrder:2}});
const allCourts=[cA,cB,cV,cT1,cT2,fA,fB];
for(const c of allCourts){for(let d=0;d<=6;d++){const wk=d===0||d===6;await prisma.facilityCourtAvailability.create({data:{courtId:c.id,dayOfWeek:d,startTime:wk?'08:00':'07:00',endTime:wk?'21:00':'22:00',isRecurring:true}});}}
for(const f of [fac1,fac2,fac3]){for(let d=0;d<=6;d++){const wk=d===0||d===6;await prisma.facilityAvailability.create({data:{facilityId:f.id,dayOfWeek:d,startTime:wk?'08:00':'07:00',endTime:wk?'21:00':'22:00',isRecurring:true}});}}
await prisma.facilityRateSchedule.create({data:{facilityId:fac1.id,name:'Base Rate',rateType:'base',hourlyRate:55,priority:0}});
await prisma.facilityRateSchedule.create({data:{facilityId:fac1.id,name:'Weekend Peak',rateType:'peak',hourlyRate:75,daysOfWeek:[5,6,0],startTime:'17:00',endTime:'21:00',priority:10}});
await prisma.facilityRateSchedule.create({data:{facilityId:fac2.id,name:'Base Rate',rateType:'base',hourlyRate:40,priority:0}});
await prisma.facilityRateSchedule.create({data:{facilityId:fac3.id,name:'Base Rate',rateType:'base',hourlyRate:65,priority:0}});
await prisma.facilityVerification.create({data:{facilityId:fac1.id,status:'approved',submittedAt:daysAgo(60),reviewedAt:daysAgo(58),expiresAt:daysFromNow(300),reviewerNotes:'All docs verified.'}});
await prisma.facilityVerification.create({data:{facilityId:fac2.id,status:'approved',submittedAt:daysAgo(45),reviewedAt:daysAgo(43),expiresAt:daysFromNow(320),reviewerNotes:'Lease verified.'}});
await prisma.review.create({data:{userId:players[0].id,facilityId:fac1.id,rating:5,comment:'Great courts!'}});
await prisma.review.create({data:{userId:players[2].id,facilityId:fac1.id,rating:4,comment:'Good facility.'}});
await prisma.review.create({data:{userId:players[1].id,facilityId:fac2.id,rating:5,comment:'Beautiful courts.'}});
await prisma.review.create({data:{userId:players[3].id,facilityId:fac2.id,rating:4,comment:'Nice club.'}});
await prisma.review.create({data:{userId:players[5].id,facilityId:fac3.id,rating:4,comment:'Decent fields.'}});
await prisma.review.create({data:{userId:players[6].id,facilityId:fac3.id,rating:3,comment:'Fields need work.'}});
console.log('Facilities, courts, availability, reviews created');
const cp:Record<string,number>={};for(const c of[cA,cB,cV])cp[c.id]=55;for(const c of[cT1,cT2])cp[c.id]=40;for(const c of[fA,fB])cp[c.id]=65;
let sc=0,rc=0;
for(const court of allCourts){for(let off=1;off<=14;off++){const date=daysFromNow(off);const wk=date.getDay()===0||date.getDay()===6;const sH=wk?8:7,eH=wk?21:22;for(let h=sH;h<eH;h++){const r=Math.random();const st=r<0.7?'available':r<0.9?'rented':'blocked';const slot=await prisma.facilityTimeSlot.create({data:{courtId:court.id,date,startTime:`${String(h).padStart(2,'0')}:00`,endTime:`${String(h+1).padStart(2,'0')}:00`,status:st,price:cp[court.id]||50,blockReason:st==='blocked'?pick(['Maintenance','Private event']):null}});sc++;if(st==='rented'){await prisma.facilityRental.create({data:{userId:pick(players).id,timeSlotId:slot.id,status:'confirmed',totalPrice:cp[court.id]||50,paymentStatus:'paid',confirmationSent:true}});rc++;}}}}
console.log(`${sc} time slots, ${rc} rentals created`);
const t1=await prisma.team.create({data:{name:'Hardwood Heroes',description:'Competitive basketball roster',sportType:'basketball',skillLevel:'intermediate',maxMembers:10,balance:250,joinFee:25,joinFeeType:'one_time',imageUrl:FAC_IMGS[0]}});
for(let i=0;i<5;i++)await prisma.teamMember.create({data:{userId:players[i].id,teamId:t1.id,role:i===0?'captain':'member'}});
const t2=await prisma.team.create({data:{name:'Net Destroyers',description:'Advanced tennis roster',sportType:'tennis',skillLevel:'advanced',maxMembers:8,balance:100,imageUrl:FAC_IMGS[1]}});
for(let i=5;i<8;i++)await prisma.teamMember.create({data:{userId:players[i].id,teamId:t2.id,role:i===5?'captain':'member'}});
const t3=await prisma.team.create({data:{name:'Thunder FC',description:'Intermediate soccer roster',sportType:'soccer',skillLevel:'intermediate',maxMembers:14,balance:180,joinFee:30,joinFeeType:'monthly',imageUrl:FAC_IMGS[2]}});
for(let i=3;i<7;i++)await prisma.teamMember.create({data:{userId:players[i].id,teamId:t3.id,role:i===3?'captain':'member'}});
const t4=await prisma.team.create({data:{name:'Spike Squad',description:'Beginner volleyball roster',sportType:'volleyball',skillLevel:'beginner',maxMembers:12,balance:0}});
for(let i=7;i<10;i++)await prisma.teamMember.create({data:{userId:players[i].id,teamId:t4.id,role:'member'}});
const t5=await prisma.team.create({data:{name:'Portland Ballers',description:'Advanced basketball roster',sportType:'basketball',skillLevel:'advanced',maxMembers:10,balance:320,imageUrl:FAC_IMGS[0]}});
for(let i=8;i<12;i++)await prisma.teamMember.create({data:{userId:players[i].id,teamId:t5.id,role:i===8?'captain':'member'}});
const t6=await prisma.team.create({data:{name:'Pickle Champs',description:'Beginner pickleball roster',sportType:'pickleball',skillLevel:'beginner',maxMembers:8,balance:50}});
for(let i=10;i<12;i++)await prisma.teamMember.create({data:{userId:players[i].id,teamId:t6.id,role:'member'}});
console.log('Rosters created');
for(const[team,amts]of[[t1,[25,25,25,25,25]],[t3,[30,30,30,30]],[t5,[50,50,50,50,120]],[t6,[25,25]]]as[any,number[]][]){let bal=0;for(const a of amts){const b=bal;bal+=a;await prisma.teamTransaction.create({data:{teamId:team.id,type:a>40?'top_up':'join_fee',amount:a,balanceBefore:b,balanceAfter:bal,description:a>40?'Top-up':'Join fee',paymentStatus:'completed',userId:pick(players).id}});}}
const lg1=await prisma.league.create({data:{name:'Portland City Basketball League',description:'Competitive city basketball league.',sportType:'basketball',skillLevel:'intermediate',organizerId:commissioner.id,leagueType:'team',leagueFormat:'season_with_playoffs',playoffTeamCount:2,isActive:true,isCertified:true,certifiedAt:daysAgo(30),pricingType:'paid',trackStandings:true,preferredGameDays:[6],preferredTimeWindowStart:'18:00',preferredTimeWindowEnd:'21:00',imageUrl:FAC_IMGS[0]}});
const s1=await prisma.season.create({data:{leagueId:lg1.id,name:'Spring 2026',startDate:daysAgo(60),endDate:daysFromNow(60),isActive:true,pricingType:'paid',duesAmount:50}});
await prisma.leagueMembership.create({data:{leagueId:lg1.id,teamId:t1.id,memberType:'roster',memberId:t1.id,seasonId:s1.id,status:'active',matchesPlayed:4,wins:3,losses:1,points:9,goalsFor:340,goalsAgainst:290,goalDifference:50}});
await prisma.leagueMembership.create({data:{leagueId:lg1.id,teamId:t5.id,memberType:'roster',memberId:t5.id,seasonId:s1.id,status:'active',matchesPlayed:4,wins:2,losses:2,points:6,goalsFor:310,goalsAgainst:330,goalDifference:-20}});
for(const m of [{h:t1.id,a:t5.id,d:-28,hs:88,as:82,o:'home_win',st:'completed'},{h:t5.id,a:t1.id,d:-21,hs:91,as:85,o:'home_win',st:'completed'},{h:t1.id,a:t5.id,d:-14,hs:95,as:78,o:'home_win',st:'completed'},{h:t5.id,a:t1.id,d:-7,hs:80,as:84,o:'away_win',st:'completed'},{h:t1.id,a:t5.id,d:7,hs:null,as:null,o:null,st:'scheduled'},{h:t5.id,a:t1.id,d:14,hs:null,as:null,o:null,st:'scheduled'}]){await prisma.match.create({data:{leagueId:lg1.id,seasonId:s1.id,homeTeamId:m.h,awayTeamId:m.a,scheduledAt:dateAtHour(daysFromNow(m.d),19),playedAt:m.st==='completed'?dateAtHour(daysFromNow(m.d),19):undefined,status:m.st,homeScore:m.hs,awayScore:m.as,outcome:m.o}});}
await prisma.leagueTransaction.create({data:{leagueId:lg1.id,seasonId:s1.id,type:'dues_received',amount:250,balanceAfter:250,description:'Hardwood Heroes dues',rosterId:t1.id}});
await prisma.leagueTransaction.create({data:{leagueId:lg1.id,seasonId:s1.id,type:'dues_received',amount:200,balanceAfter:450,description:'Portland Ballers dues',rosterId:t5.id}});
await prisma.leagueTransaction.create({data:{leagueId:lg1.id,seasonId:s1.id,type:'court_cost',amount:-110,balanceAfter:340,description:'Court rental'}});
for(let i=0;i<5;i++)await prisma.playerDuesPayment.upsert({where:{playerId_rosterId_seasonId:{playerId:players[i].id,rosterId:t1.id,seasonId:s1.id}},update:{},create:{playerId:players[i].id,rosterId:t1.id,seasonId:s1.id,amount:50,platformFee:0.5,paymentStatus:'succeeded'}});
for(let i=8;i<12;i++)await prisma.playerDuesPayment.upsert({where:{playerId_rosterId_seasonId:{playerId:players[i].id,rosterId:t5.id,seasonId:s1.id}},update:{},create:{playerId:players[i].id,rosterId:t5.id,seasonId:s1.id,amount:50,platformFee:0.5,paymentStatus:'succeeded'}});
const lg2=await prisma.league.create({data:{name:'Casco Bay Tennis Open',description:'Single elimination tennis tournament.',sportType:'tennis',skillLevel:'advanced',organizerId:commissioner.id,leagueType:'team',leagueFormat:'tournament',eliminationFormat:'single_elimination',pricingType:'free',isActive:true,imageUrl:FAC_IMGS[1]}});
const s2=await prisma.season.create({data:{leagueId:lg2.id,name:'Summer 2026',startDate:daysFromNow(30),endDate:daysFromNow(90),isActive:true}});
await prisma.leagueMembership.create({data:{leagueId:lg2.id,teamId:t2.id,memberType:'roster',memberId:t2.id,seasonId:s2.id,status:'active'}});
await prisma.leagueMembership.create({data:{leagueId:lg2.id,teamId:t6.id,memberType:'roster',memberId:t6.id,seasonId:s2.id,status:'active'}});
const lg3=await prisma.league.create({data:{name:'Portland Pickup Soccer League',description:'Casual pickup soccer league.',sportType:'soccer',skillLevel:'intermediate',organizerId:commissioner.id,leagueType:'pickup',leagueFormat:'season',pricingType:'free',isActive:true,imageUrl:FAC_IMGS[2]}});
const s3=await prisma.season.create({data:{leagueId:lg3.id,name:'Spring 2026',startDate:daysAgo(30),endDate:daysFromNow(60),isActive:true}});
for(let i=0;i<8;i++)await prisma.leagueMembership.create({data:{leagueId:lg3.id,userId:players[i].id,memberType:'user',memberId:players[i].id,seasonId:s3.id,status:'active',matchesPlayed:2+i,wins:1+(i%3),losses:i%2,draws:i%2,points:3+(i%3)*2}});
console.log('Leagues created');
const evts:any[]=[];
for(const c of [{t:'Tuesday Night Hoops',sp:'basketball',f:fac1,d:2,h:19,mx:10,pr:15},{t:'Friday Basketball Run',sp:'basketball',f:fac1,d:5,h:18,mx:12,pr:10},{t:'Tennis Mixer',sp:'tennis',f:fac2,d:3,h:10,mx:8,pr:20},{t:'Soccer Pickup',sp:'soccer',f:fac3,d:4,h:17,mx:14,pr:10},{t:'Volleyball Open Gym',sp:'volleyball',f:fac1,d:6,h:19,mx:16,pr:15}]){const e=await prisma.event.create({data:{title:c.t,description:`Casual ${c.sp} pickup.`,sportType:c.sp,skillLevel:'all_levels',eventType:'pickup',status:'active',startTime:dateAtHour(daysFromNow(c.d),c.h),endTime:dateAtHour(daysFromNow(c.d),c.h+2),maxParticipants:c.mx,currentParticipants:4,price:c.pr,equipment:['Water bottle','Athletic shoes'],rules:'Fair play.',imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:c.f.id}});evts.push(e);}
for(const[i,d]of[7,10,14].entries()){const e=await prisma.event.create({data:{title:`League Game ${i+1}`,description:'League match.',sportType:'basketball',skillLevel:'intermediate',eventType:'game',status:'active',startTime:dateAtHour(daysFromNow(d),19),endTime:dateAtHour(daysFromNow(d),21),maxParticipants:10,price:0,rules:'League rules.',imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:fac1.id}});evts.push(e);}
for(let i=0;i<2;i++){const e=await prisma.event.create({data:{title:`Invite-Only Hoops ${i+1}`,description:'By invitation only.',sportType:'basketball',skillLevel:'advanced',eventType:'pickup',status:'active',startTime:dateAtHour(daysFromNow(4+i),18),endTime:dateAtHour(daysFromNow(4+i),20),maxParticipants:10,price:20,eligibilityIsInviteOnly:true,isPrivate:false,minimumPlayerCount:6,imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:fac1.id}});evts.push(e);}
for(let i=0;i<2;i++){const e=await prisma.event.create({data:{title:`Private Session ${i+1}`,description:'Private event.',sportType:'tennis',skillLevel:'intermediate',eventType:'practice',status:'active',startTime:dateAtHour(daysFromNow(3+i*2),17),endTime:dateAtHour(daysFromNow(3+i*2),19),maxParticipants:8,currentParticipants:3,price:25,isPrivate:true,invitedUserIds:[players[0].id,players[1].id,players[2].id],imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:fac2.id}});evts.push(e);}
const pastEvts:any[]=[];
for(const[i,ago]of[7,14,21].entries()){const sp=['basketball','soccer','tennis'][i];const fc=[fac1,fac3,fac2][i];const st=dateAtHour(daysAgo(ago),18);const e=await prisma.event.create({data:{title:`Past ${sp.charAt(0).toUpperCase()+sp.slice(1)} Game`,description:'Completed.',sportType:sp,skillLevel:'intermediate',eventType:'pickup',status:'completed',startTime:st,endTime:dateAtHour(daysAgo(ago),20),maxParticipants:10,currentParticipants:6,price:10,imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:fc.id}});pastEvts.push(e);evts.push(e);for(let p=0;p<6;p++){await prisma.gameParticipation.create({data:{userId:players[p].id,eventId:e.id,playedAt:st,eventType:'pickup',participantCount:6,gameScore:0.5+Math.random(),votesReceived:p<3?1:0,votesCast:1,gameRating:1+Math.random()*0.5}});await prisma.playerVote.create({data:{eventId:e.id,voterId:players[p].id,votedForId:players[(p+1)%6].id}});}for(let s=0;s<4;s++)await prisma.salute.create({data:{eventId:e.id,fromUserId:players[s].id,toUserId:players[(s+2)%6].id}});}
for(let i=0;i<2;i++){const e=await prisma.event.create({data:{title:`Cancelled ${i===0?'Basketball':'Soccer'} Game`,description:'Cancelled.',sportType:i===0?'basketball':'soccer',skillLevel:'intermediate',eventType:'pickup',status:'cancelled',cancellationReason:i===0?'Not enough players':'Weather',startTime:dateAtHour(daysFromNow(2+i),18),endTime:dateAtHour(daysFromNow(2+i),20),maxParticipants:10,price:10,imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:i===0?fac1.id:fac3.id}});evts.push(e);}
const gfc=await prisma.event.create({data:{title:'Roster-Covered Basketball',description:'Fees covered by roster.',sportType:'basketball',skillLevel:'intermediate',eventType:'game',status:'active',startTime:dateAtHour(daysFromNow(8),19),endTime:dateAtHour(daysFromNow(8),21),maxParticipants:10,price:0,isGroupFeeCovered:true,coveringTeamId:t1.id,imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:fac1.id}});evts.push(gfc);
for(let i=0;i<2;i++){const e=await prisma.event.create({data:{title:i===0?'Young Adults Soccer':'Under 35 Basketball',description:'Age-restricted.',sportType:i===0?'soccer':'basketball',skillLevel:'all_levels',eventType:'pickup',status:'active',startTime:dateAtHour(daysFromNow(5+i*3),17),endTime:dateAtHour(daysFromNow(5+i*3),19),maxParticipants:12,price:10,ageRestricted:true,eligibilityMinAge:18,eligibilityMaxAge:35,imageUrl:pick(EVT_IMGS),organizerId:commissioner.id,facilityId:i===0?fac3.id:fac1.id}});evts.push(e);}
console.log(`${evts.length} events created`);
for(let e=0;e<5;e++){for(let p=0;p<4;p++){await prisma.booking.create({data:{userId:players[p].id,eventId:evts[e].id,bookingType:'event',totalPrice:evts[e].price,status:'confirmed',paymentStatus:'paid'}});}}
for(const pe of pastEvts){for(let p=0;p<3;p++){await prisma.booking.create({data:{userId:players[p].id,eventId:pe.id,bookingType:'event',totalPrice:pe.price,status:'confirmed',paymentStatus:'paid',debriefSubmitted:true}});}}
for(let e=5;e<8;e++){const bk=await prisma.booking.create({data:{userId:commissioner.id,eventId:evts[e].id,bookingType:'event',totalPrice:0,status:'confirmed',paymentStatus:'paid',bookingHostType:'league_commissioner',bookingHostId:commissioner.id}});await prisma.bookingParticipant.create({data:{bookingId:bk.id,rosterId:t1.id,role:'home',escrowAmount:55}});await prisma.bookingParticipant.create({data:{bookingId:bk.id,rosterId:t5.id,role:'away',escrowAmount:55}});}
console.log('Bookings created');
const pc1=await prisma.promoCode.create({data:{code:'MUSTER30',trialDurationDays:30,createdByAdminId:admin.id}});
const pc2=await prisma.promoCode.create({data:{code:'TRYIT',trialDurationDays:14,createdByAdminId:admin.id}});
await prisma.promoCode.create({data:{code:'LAUNCH2026',trialDurationDays:60,createdByAdminId:admin.id}});
await prisma.promoCodeRedemption.create({data:{userId:players[0].id,promoCodeId:pc1.id,selectedTier:'pro'}});
await prisma.promoCodeRedemption.create({data:{userId:players[1].id,promoCodeId:pc2.id,selectedTier:'elite'}});
console.log('Promo codes created');
console.log('\n🎉 Seed complete!');
console.log('════════════════════════════════════════');
console.log(`  Users: 17 | Facilities: 3 | Courts: 7`);
console.log(`  Time Slots: ${sc} | Rentals: ${rc}`);
console.log(`  Rosters: 6 | Leagues: 3 | Events: ${evts.length}`);
console.log('  Password: Muster123!');
console.log('  admin@muster.test | owner@muster.test | commissioner@muster.test');
console.log('  player1-12@muster.test | dep1@muster.test | dep2@muster.test');
console.log('════════════════════════════════════════\n');
}
main().catch((e)=>{console.error('Seed failed:',e);process.exit(1);}).finally(async()=>{await prisma.$disconnect();});
